server:
  port: 1099

spring:
  config:
    activate:
      on-profile: dev

  application:
    name: sysgei

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dbsysgei
    username: sysgei
    password: sysgei
  liquibase:
    contexts: dev
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog/master.xml
    default-schema: public
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    generate-ddl: true
    database: postgresql



