server:
  port: 1099

spring:
  config:
    activate:
      on-profile: prod

  application:
    name: sysgei

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dbsysgei
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
    database: postgresql
debug: true

